### ISSUE TITLE
 Bug Report: Homepage Bug Fixed

### ISSUE THREAD

**Issue by SoumikGhosh9** [Parnab03/Tech6Sense#5]
### 🔖 Bug Description

There was a bug in homepage of the website mainly there is a width issue, and properly fix the Homepage Component files.
In the latest version the bug fixed. 

### 🔄 Steps to Reproduce

The components are was not in a  proper format now its formatted.

### ✔️ Expected Behavior

The components are was not in a  proper format now its formatted.
Clearly outline how the website or application should behave under normal conditions. Be specific to ensure there's no ambiguity.

### 📷 Screenshots

![Screenshot (182)](https://github.com/user-attachments/assets/ce622c38-9ffd-4558-b2bb-4b7edb42e32a)

### ✔️ Checklist

- [X] I have confirmed this bug exists in the latest version.
- [X] I have checked existing issues to avoid duplicates.
- [X] I have read and understood the [Tech6Sense Contributing Guidelines](https://github.com/Parnab03/Tech6Sense/blob/main/CONTRIBUTING.md).
- [X] I have reviewed the [Code of Conduct](https://github.com/Parnab03/Tech6Sense/blob/main/CODE_OF_CONDUCT.md) and agree to abide by it.

**Comment by Parnab03** [comment]
completed by @Parnab03
